---
server:
  assets_path: /go/src/github.com/lzxz1234/padlock-cloud/assets
  port: 8081
  base_url: https://xxxxxx.xxxx.xx
  cors: true
leveldb:
  path: /db
email:
  server: smtp.xxxx.xx
  port: 80
  user: xxx@xxxx.xx
  password: xxxxxxxx
log:
  log_file: /log.txt
  err_file: /err.txt
  notify_errors: 314946925@qq.com